apiVersion: v1
kind: Service
metadata:
  name: pyspark-jupyter
spec:
  selector:
    app: pyspark-jupyter
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
    - name: web-ui
      port: 8080
      targetPort: 8080
    - name: master
      port: 7077
      targetPort: 7077
    - name: master-rest
      port: 6066
      targetPort: 6066
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyspark-jupyter
spec:
  selector:
    matchLabels:
      app: pyspark-jupyter
  template:
    metadata:
      labels:
        app: pyspark-jupyter
    spec:
      containers:
        - name: pyspark-jupyter
          image: jupyter/pyspark-notebook:7a0c7325e470
          ports:
            - containerPort: 8888
            - containerPort: 4040
            - containerPort: 4041
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
          volumeMounts:
            - name: mount-directory
              mountPath: /home/jovyan/work
      volumes:
        - name: mount-directory
          hostPath:
            path: <path> ## mount-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: bde2020/spark-master:2.4.4-hadoop2.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 7077
            - containerPort: 6066
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bde2020/spark-worker:2.4.4-hadoop2.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
