{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sample_spark_standalone.serviceAccountName" . }}
  labels:
{{ include "sample_spark_standalone.labels" . | indent 4 }}
{{- end -}}
