version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - mysql-net
  app:
    build: ./app
    image: mysql-connect-sample:1.0
    environment:
      - HOST=db
      - PORT=3306
      - USER=user
      - PASSWORD=password
    depends_on:
      - db
    networks:
      - mysql-net

networks:
  mysql-net:
