version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    networks:
      - esnet
  cerebro:
    image: lmenezes/cerebro:0.8.3
    ports:
      - 9000:9000
    networks:
      - esnet
    depends_on:
      - es
  script:
    build: ./scripts
    image: setup-es-script:1.0
    networks:
      - esnet
    depends_on:
      - es
    environment:
      - ES_HOST=es

networks:
  esnet:
