apiVersion: v1
kind: Service
metadata:
  name: pyspark-jupyter
spec:
  selector:
    app: pyspark-jupyter
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
    - name: master
      port: 7077
      targetPort: 7077
    - name: master-rest
      port: 6066
      targetPort: 6066
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: spark-client
spec:
  selector:
    app: spark-client
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-web-ui
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-web-ui
spec:
  selector:
    app: spark-worker
  ports:
  - name: web-ui
    port: 8081
    targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyspark-jupyter
spec:
  selector:
    matchLabels:
      app: pyspark-jupyter
  template:
    metadata:
      labels:
        app: pyspark-jupyter
    spec:
      containers:
        - name: pyspark-jupyter
          image: jupyter/pyspark-notebook:7a0c7325e470
          ports:
            - containerPort: 8888
            - containerPort: 4040
            - containerPort: 4041
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
          volumeMounts:
            - name: mount-scripts
              mountPath: /home/jovyan/work
            - name: mount-data
              mountPath: /tmp/data
      volumes:
        - name: mount-scripts
          hostPath:
            path: /Users/wararaki/projects/scrapbox2/k8s_sample/sample_spark_load_data_k8s/work ## mount-path
        - name: mount-data
          hostPath:
            path: /Users/wararaki/projects/scrapbox2/k8s_sample/sample_spark_load_data_k8s/data ## mount-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: bde2020/spark-master:2.4.4-hadoop2.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 7077
            - containerPort: 6066
          volumeMounts:
            - name: mount-data
              mountPath: /tmp/data
      volumes:
        - name: mount-data
          hostPath:
            path: /Users/wararaki/projects/scrapbox2/k8s_sample/sample_spark_load_data_k8s/data ## mount-path
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bde2020/spark-worker:2.4.4-hadoop2.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          volumeMounts:
            - name: mount-data
              mountPath: /tmp/data
      volumes:
        - name: mount-data
          hostPath:
            path: /Users/wararaki/projects/scrapbox2/k8s_sample/sample_spark_load_data_k8s/data ## mount-path
