version: "3.7"
services:
  default_db:
    image: mysql:5.7
    container_name: mysql-default
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
  fixed_db:
    image: mysql:5.7
    container_name: mysql-utf8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3307:3307
    environment:
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_TCP_PORT=3307
