version: "3"
services:
  backend:
    build: ./backend
    image: backend-vis:1.0
    ports: 
      - 8000:8000
  frontend:
    build: ./frontend
    image: frontend-vis:1.0
    ports:
      - 3000:3000

networks:
  visnet:
