version: "3.7"
services:
  notebook:
    image: jupyter/pyspark-notebook:7a0c7325e470
    container_name: notebook
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - spark-net
  master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-net
  worker:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker
    depends_on:
      - master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://master:7077
    networks:
      - spark-net

networks:
  spark-net:
